# Generated by Django 3.2.9 on 2021-12-07 17:15

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211203_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
