# Generated by Django 3.2.9 on 2021-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
